apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $CLUSTER_NAME
  region: $REGION

accessConfig:
  authenticationMode: API

iam:
  withOIDC: true

addons:
- name: eks-pod-identity-agent
  version: latest

autoModeConfig:
  enabled: true